package models

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

type Availabilities []AvailabilityElement

type AvailabilityElement struct {
	Region      Region              `json:"region"`
	Datacenters []DatacenterElement `json:"datacenters"`
	Hardware    string              `json:"hardware"`
}

type DatacenterElement struct {
	Datacenter   DatacenterEnum   `json:"datacenter"`
	Availability AvailabilityEnum `json:"availability"`
}

type AvailabilityEnum string

const (
	The1HHigh   AvailabilityEnum = "1H-high"
	The1HLow    AvailabilityEnum = "1H-low"
	The240H     AvailabilityEnum = "240H"
	The24H      AvailabilityEnum = "24H"
	The72H      AvailabilityEnum = "72H"
	Unavailable AvailabilityEnum = "unavailable"
)

type DatacenterEnum string

const (
	Bhs     DatacenterEnum = "bhs"
	Default DatacenterEnum = "default"
	Fra     DatacenterEnum = "fra"
	Gra     DatacenterEnum = "gra"
	Hil     DatacenterEnum = "hil"
	Lon     DatacenterEnum = "lon"
	Rbx     DatacenterEnum = "rbx"
	Sbg     DatacenterEnum = "sbg"
	Sgp     DatacenterEnum = "sgp"
	Syd     DatacenterEnum = "syd"
	Vin     DatacenterEnum = "vin"
	Waw     DatacenterEnum = "waw"
)

type Region string

const (
	Apac         Region = "apac"
	Europe       Region = "europe"
	NorthAmerica Region = "northAmerica"
)
