package models

// Generated by https://quicktype.io

type Config struct {
	Servers       []string `json:"servers"`
	Region        string   `json:"region"`
	Notifier      string   `json:"notifier"`
	EmailSender   string   `json:"email_sender"`
	EmailPassword string   `json:"email_password"`
	SMTPHost      string   `json:"smtp_host"`
	EmailReceiver string   `json:"email_receiver"`
	EmailPort     string   `json:"email_port"`
	EmailSubject  string   `json:"email_subject"`
}
