package models

import "gorm.io/gorm"

// Generated by https://quicktype.io

type ServerTypes map[string]string

type ServerInfo struct {
	gorm.Model
	ID           string
	Region       string
	Availability string
	Url          string
}
